version: '3'
services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      NODE_DB_HOST: db
      NODE_DB_USER: root
      NODE_DB_PASS: password
      NODE_DB_NAME: sample
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306
volumes:
  db-volume: